### ISSUE TITLE
Properly Handle Pipes

### ISSUE THREAD

**Issue by ariporad** [nfischer/BashToShellJS#8]
It would appear that B2SHJS isn't fully aware of what can go on the right side of pipes. For example:

In:

```bash
cat foo | grep
```

Out:

```javascript
cat('foo').exec('grep');
```

Where as it should be (at lease once `shelljs@0.7.0` comes out):

```javascript
cat('foo').grep();
```

**Comment by nfischer** [comment]
`cat foo | grep` doesn't work because `grep()` takes one or more arguments. Try:

```
cat foo | grep 'o'
```

and you should see:

```
cat('foo').grep('o');
```

It defaults to an `exec()` whenever parsing the individual command fails, which is designed to help indicate errors to the user.

**Comment by ariporad** [comment]
Whoops! My Bad.

**Comment by nfischer** [comment]
I'm thinking of finding a better way to document that. It probably could be more intuitive.
